### ISSUE TITLE
Authorization to replace broccoli.instances.prefix and broccoli.permissions.mode

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#145]
### Tasks

- [x] a role assigned (`administrator`, `operator`, `user`). Depending on this role, the access is managed on the HTTP API and UI. (https://github.com/t2v/play2-auth#changing-the-authorization-depending-on-the-request-parameters + if everyone can access https://github.com/t2v/play2-auth#for-action-that-doesnt-require-authorization else normal)
- [x] a job prefix configured to determine which jobs he is allowed to see
- [x] use `BroccoliRoleAuthentication` if you need role specific endpoints
- [x] this makes `broccoli.instances.prefix` obsolete and we should remove it
- [x] 403 should tell you that you are logged out on the UI. There needs to be another code for not enough permissions.
- [x] this makes `broccoli.permissions.mode` obsolete and we should remove it (also from the Wiki and README)
- [x] change the about section in the Wiki to reflect that prefix is gone
- [x] explain in Wiki that role and regex are optional (and what the defaults are)
- [x] document how to configure a user account instance regex (`broccoli.auth.conf.accounts=[{username:admin,password:admin,instanceRegex=".*"}]`)

```
private def checkPrefix[F, T](id: String)(f: => Try[T]): Try[T] = {
    if (id.startsWith(nomadJobPrefix)) {
      f
    } else {
      Failure(PrefixViolationException(id, nomadJobPrefix))
    }
  }
```

### Issue Links

Depends on: #136
