### ISSUE TITLE
Elm?

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#181]
### Problem

https://www.elm-tutorial.org/en/

I'm sick and tired of this `bs.js`... Shall I give it a try?

### References

- Play Template (not needed?) https://gist.github.com/newlandsvalley/801b2d6164e4187f9a08
- CSS https://gist.github.com/coreytrampe/a120fac4959db7852c0f
- Layout? http://package.elm-lang.org/packages/debois/elm-mdl/latest/ (not yet elm 0.18)
- Modals? https://github.com/krisajenkins/elm-dialog
- Bootstrap.js? http://getbootstrap.com/javascript/#collapse => https://www.npmjs.com/package/bootstrap-webpack
- Animations => https://github.com/mdgriffith/elm-style-animation
- Animations using only css? https://github.com/daneden/animate.css https://daneden.github.io/animate.css/
- Forms? http://package.elm-lang.org/packages/etaque/elm-form/latest

### Notes

- `` packages installed using `npm i webpack@1 elm-webpack-loader@3 file-loader@0 style-loader@0 css-loader@0 url-loader@0 ace-css@1 font-awesome@4 -S`
- `npm run build` to build the application
- We would need bootstrap?

### ToDo

- [x] template upgrade / migration is solved in the UI
- [x] things that won't work should already be prevented in the UI
- [x] html tests? http://package.elm-lang.org/packages/eeue56/elm-html-test/latest
- [x] get rid of any unused package
- [x] check that everything compiles on CI
- [x] add tests
- [x] document that design is now super responsive and mobile first (actually verify)
- [x] document changes in the API + WS
- [x] contextual classes for tables: http://getbootstrap.com/css/#tables-contextual-classes (`.active`  for the instances you request more information about)
- [x] responsive tables: http://getbootstrap.com/css/#tables-responsive, which collapses everything to something extendable (similar to the navigation) except the instance id and status worst case?
- [x] putting templates in panels with tables? http://getbootstrap.com/components/#panels-tables
- [x] mobile ready tables showing only the important parts (http://getbootstrap.com/css/#responsive-utilities-classes)

### Browser Compatibility

![grafik](https://cloud.githubusercontent.com/assets/3427394/26577597/30eee3c4-452d-11e7-8e70-d1dff4c8a76d.png)

![grafik](https://cloud.githubusercontent.com/assets/3427394/26577647/5ef691cc-452d-11e7-8338-e266e819d6a1.png)
