### ISSUE TITLE
Use HOCON for template meta information

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#300]
## Problem 

HOCON > JSON, so the meta.json should be HOCON and parsing should be done using [pureconfig](https://github.com/pureconfig/pureconfig).

## Documentation Changes

- [x] `meta.json` will no longer be supported and `template.conf` should be used. That should be documented in the [Upgrading to 0.8.0](https://github.com/FRosner/cluster-broccoli/wiki/Upgrading-to-0.8.0) section. However, HOCON is a superset of JSON so the change will be backwards compatible.
- [ ] `meta.json` is now called `template.conf` and uses HOCON syntax. That should be documented in the [Templates](https://github.com/FRosner/cluster-broccoli/wiki/Templates#meta-information-file) section of the Wiki.

## ToDo

- [x] check if `meta.json` being renamed to `template.conf` will be backwards compatible => it is
