### ISSUE TITLE
Different persistent back-ends (especially a thread-safe one :) )

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#45]
### Problem

When the instances are persisted in a file it needs to be locked to avoid concurrent access. However, this prevents us from starting multiple Broccoli instances for load balancing or having different configurations.

### Solution

Support CouchDB as a persistent instance storage and talk to it over the HTTP API.
This requires us to rework the configuration properties:
- [x] `broccoli.templates.storage.type` how to 'persist' templates (currently only `file` supported, which is the directory structure)
- [x] `broccoli.templates.storage.url` path to look for templates (folder path if type is `fs`)
- [x] `broccoli.instances.storage.type` how to 'persist' templates (`fs` or `couchdb`)
- [x] `broccoli.instances.storage.url` path to look for instances (directory if `fs`, HTTP endpoint of CouchDB if `couchdb`)
- [x] remove `broccoli.templatesDir` and `broccoli.instancesFile` (search all code and documentation)
- [x] Broccoli must only return 200 on an operation if it was successful. So the HTTP API should be blocking in order to avoid users making changes an realizing that someone else overwrote them.
- [x] Link in README + Wiki page explaining the storage back-ends and configuration options. Especially important in order to know how to handle version upgrades with breaking schema changes.
- [x] Nomad job prefix still needs to be respected
- [x] Actually it doesn't make any sense to persist the service and job status information.
### References
- https://hub.docker.com/_/couchdb/
- http://docs.couchdb.org/en/2.0.0/intro/api.html

### Tasks

- [x] Change the file back-end to a directory based back-end so that each instance gets its own JSON. Reason behind that is that 1) it is easier to navigate and manually delete instances, 2) if during a write something gets corrupted it's only one instance and 3) it will be consistent with the DB back-end where we are writing also instance by instance mainly to avoid version conflicts if people edit different instances. (#121)
- [x] The DB back-end needs to regularly poll the DB for new versions because otherwise you won't notice if another Broccoli is making changes? Or shall we say that multiple changing Broccolis is not supported? => ask the back-end on every request.
- [x] Should Broccoli store any state in-memory or just query the back-end on every request? => After discussing with @Gerrrr we decided not to keep any state but always query the back-end. The queries should be blocking so the HTTP API is only returning 200 if the request was successful. Later we can make it async.
- [x] How to unit test CouchDB? => https://www.playframework.com/documentation/2.5.x/ScalaTestingWebServiceClients 
- [x] Add an http-api-test that adds 1000 instances and checks whether they can get retrieved properly (with couchdb)
- [x] no `FIXME`s and no `TODO`s left around this topic
- [x] script in the Wiki documentation that transfers instances from one broccoli to another (for migrating between storages). it should ask the first one and submit it to the second one
