### ISSUE TITLE
(C)leaner Docker Image

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#55]
### Problem

Travis should push the image containing only the binaries and not activator. openjdk:8-jre should be used as a base image to be lean and small. The activator image can still remain in a different folder so people can use it for quick development.
### References
- https://sebest.github.io/post/using-travis-ci-to-build-docker-images/
### Tasks
- [x] adjust README example
- [x] adjust README dockerhub badge
- [x] different tags are explained in dockerhub
- [x] travis only pushes to dockerhub on master
